### ISSUE TITLE
Issue with CUDA memory...

### ISSUE THREAD

**Issue by MrMxyzptlk** [M4K4R/Gradio-V-Express#1]
Thank you for this! Worked like a charm after installing Python 3.9 in venv; fails with 3.12.

I'm running into a memory issue; is there somewhere I can adjust how it's being allocated? Here is the current error; I'm running on a 12GB 3060.

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 41.05 GiB (GPU 0; 12.00 GiB total capacity; 12.61 GiB already allocated; 0 bytes free; 12.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Thank you once again...

**Comment by MrMxyzptlk** [comment]
I guess I had to long an audio clip; would you happen to know a good length for 12GB?
I had a 3 minute long song; once I tried a 5 second snippet, it worked.

**Comment by srijat2001** [comment]
Hey, @MrMxyzptlk. I am facing issues with the output, my 15 sec audio clip is taking around 30 min to produce video output. I am currently using A10G hardware in hugging space
